from app.schemas.common import LLMProvider


def get_provider_presets() -> list[LLMProvider]:
    return [
        LLMProvider(
            id="dashscope",
            display_name="阿里云百炼 / 通义千问 / DashScope",
            provider_family="dashscope",
            aliases=["aliyun_bailian", "qwen"],
            api_key_env="DASHSCOPE_API_KEY",
            openai_compatible=True,
            notes="Model name is supplied by user configuration.",
        ),
        LLMProvider(
            id="qianfan",
            display_name="百度千帆 / 文心 / Qianfan",
            provider_family="qianfan",
            aliases=["baidu_wenxin", "ernie"],
            api_key_env="QIANFAN_API_KEY",
            openai_compatible=True,
            notes="Model name is supplied by user configuration.",
        ),
        LLMProvider(
            id="hunyuan",
            display_name="腾讯混元 / Hunyuan",
            provider_family="hunyuan",
            aliases=["tencent_hunyuan"],
            api_key_env="HUNYUAN_API_KEY",
            openai_compatible=True,
            notes="Model name is supplied by user configuration.",
        ),
        LLMProvider(
            id="volcark",
            display_name="火山方舟 / 豆包 / VolcArk",
            provider_family="volcark",
            aliases=["volcengine_ark", "doubao"],
            api_key_env="VOLCARK_API_KEY",
            openai_compatible=True,
            notes="Model name is supplied by user configuration.",
        ),
        LLMProvider(
            id="zhipu",
            display_name="智谱 AI / GLM / Zhipu",
            provider_family="zhipu",
            aliases=["glm"],
            api_key_env="ZHIPU_API_KEY",
            openai_compatible=True,
            notes="Model name is supplied by user configuration.",
        ),
        LLMProvider(
            id="deepseek",
            display_name="DeepSeek",
            provider_family="deepseek",
            aliases=["deepseek"],
            api_key_env="DEEPSEEK_API_KEY",
            openai_compatible=True,
            notes="Model name is supplied by user configuration.",
        ),
        LLMProvider(
            id="kimi",
            display_name="Moonshot / Kimi",
            provider_family="kimi",
            aliases=["moonshot"],
            api_key_env="KIMI_API_KEY",
            openai_compatible=True,
            notes="Model name is supplied by user configuration.",
        ),
        LLMProvider(
            id="minimax",
            display_name="MiniMax",
            provider_family="minimax",
            aliases=["abab"],
            api_key_env="MINIMAX_API_KEY",
            openai_compatible=True,
            notes="Model name is supplied by user configuration.",
        ),
        LLMProvider(
            id="spark",
            display_name="科大讯飞 / 星火 / Spark",
            provider_family="spark",
            aliases=["iflytek_spark"],
            api_key_env="SPARK_API_KEY",
            openai_compatible=True,
            notes="Model name is supplied by user configuration.",
        ),
        LLMProvider(
            id="openai_compatible_custom",
            display_name="OpenAI-compatible Custom Provider",
            provider_family="openai_compatible",
            aliases=["custom"],
            api_key_env=None,
            openai_compatible=True,
            notes="User supplies base URL, API key env var, and model name.",
        ),
        LLMProvider(
            id="local",
            display_name="Local Provider / Ollama / vLLM",
            provider_family="local",
            aliases=["ollama", "vllm"],
            api_key_env=None,
            openai_compatible=True,
            local_provider=True,
            notes="Reserved for local OpenAI-compatible runtimes.",
        ),
    ]
